<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class JobsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('jobs')->insert([
            'job_title' => 'Software Development Engineer',
            'fecha' => '2023/08/27',
            'job_type' => 'Full Time',
            'company_name' => 'Amazon',
            'contingency' => false,
            'location_full' => 'TN-Nashville ; TX-Austin ; WA-Seattle ;',
            'url' => 'https://www.amazon.jobs/en/jobs/2229899/software-development-engineer',
            'perks' => 'remotefriendly ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2 ;',
            'seniority' => 'Mid Level',
            'seniority_slug' => 'mid-level',
            'functional_area' => 'Engineering',
            'functional_area_slug' => 'engineering',
        ]);
        DB::table('jobs')->insert([
            'job_title' => 'Security Architect',
            'fecha' => '2023/08/03',
            'job_type' => 'Full Time',
            'company_name' => 'American Tower Corporation',
            'contingency' => false,
            'location_full' => 'MA-Other ;',
            'url' => 'https://www.americantower.com/',
            'perks' => '',
            'seniority' => 'Senior Level',
            'seniority_slug' => 'senior-level',
            'functional_area' => 'IT & Cybersecurity',
            'functional_area_slug' => 'it-cybersecurity',
        ]);
        DB::table('jobs')->insert([
            'job_title' => 'Director of Product Management, Growth and Adoption',
            'fecha' => '2023/08/23',
            'job_type' => 'Full Time',
            'company_name' => 'Asana',
            'contingency' => false,
            'location_full' => 'CA-San Francisco ;',
            'url' => 'https://boards.greenhouse.io/asana?gh_src=77d2661c1us',
            'perks' => 'remotefriendly ; unlimitedvacation ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2 ;',
            'seniority' => 'Management',
            'seniority_slug' => 'z-management',
            'functional_area' => 'Product',
            'functional_area_slug' => 'product',
        ]);
        DB::table('jobs')->insert([
            'job_title' => 'Director of Product Management, Orchestrate',
            'fecha' => '2023/08/23',
            'job_type' => 'Full Time',
            'company_name' => 'Asana',
            'contingency' => false,
            'location_full' => 'CA-San Francisco ;',
            'url' => 'https://boards.greenhouse.io/asana?gh_src=77d2661c1us',
            'perks' => 'remotefriendly ; unlimitedvacation ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2 ;',
            'seniority' => 'Senior Level',
            'seniority_slug' => 'senior-level',
            'functional_area' => 'Product',
            'functional_area_slug' => 'product',
        ]);
        DB::table('jobs')->insert([
            'job_title' => 'Senior Software Engineer',
            'fecha' => '2023/08/13',
            'job_type' => 'Internship',
            'company_name' => 'Asana',
            'contingency' => false,
            'location_full' => 'IL-Chicago ;',
            'url' => 'https://www.mcmaster.com/careers',
            'perks' => '',
            'seniority' => 'Mid Level',
            'seniority_slug' => 'mid-level',
            'functional_area' => 'Engineering',
            'functional_area_slug' => 'engineering',
        ]);
        DB::table('jobs')->insert([
            'job_title' => 'Data Integration Specialist',
            'fecha' => '2023/08/28',
            'job_type' => 'Full Time',
            'company_name' => 'Black Knight',
            'contingency' => false,
            'location_full' => 'Remote ; Hybrid ;',
            'url' => 'https://blackknight.wd1.myworkdayjobs.com/BKC/0/refreshFacet/318c8bb6f553100021d223d9780d30be',
            'perks' => '',
            'seniority' => 'Mid Level',
            'seniority_slug' => 'mid-level',
            'functional_area' => 'Data & Analytics',
            'functional_area_slug' => 'data-analytics',
        ]);
        DB::table('jobs')->insert([
            'job_title' => 'Lead Software Engineer - Identity (Remote)',
            'fecha' => '2023/08/13',
            'job_type' => 'Full Time',
            'company_name' => 'Black Rock',
            'contingency' => false,
            'location_full' => 'Remote ;',
            'url' => 'https://newrelic.com/',
            'perks' => 'remotefriendly ; unlimitedvacation ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2 ;',
            'seniority' => 'Senior Level',
            'seniority_slug' => 'senior-level',
            'functional_area' => 'Engineering',
            'functional_area_slug' => 'engineering',
        ]);
        DB::table('jobs')->insert([
            'job_title' => 'Senior Android Developer',
            'fecha' => '2023/08/03',
            'job_type' => 'Temporary',
            'company_name' => 'Bounteous',
            'contingency' => true,
            'location_full' => 'Mexico ; Mexico-Remote ;',
            'url' => 'https://www.bounteous.com',
            'perks' => '',
            'seniority' => 'Senior Level',
            'seniority_slug' => 'senior-level',
            'functional_area' => 'IT & Cybersecurity',
            'functional_area_slug' => 'it-cybersecurity',
        ]);
        DB::table('jobs')->insert([
            'job_title' => 'Sr Mobile UX/UI Designer',
            'fecha' => '2023/08/30',
            'job_type' => 'Internship',
            'company_name' => 'Charles Schwab',
            'contingency' => false,
            'location_full' => 'AZ-Phoenix ; CA-San Francisco ; FL-Orlando ; IL-Chicago ; IN-Indianapolis ; MI-Other ; MO-St. Louis ; NJ-Jersey City ; TX-Austin ; TX-Dallas ;',
            'url' => 'https://jobs.schwabjobs.com/',
            'perks' => 'remotefriendly ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2 ;',
            'seniority' => 'Senior Level',
            'seniority_slug' => 'senior-level',
            'functional_area' => 'Design',
            'functional_area_slug' => 'design',
        ]);
        DB::table('jobs')->insert([
            'job_title' => 'Project Manager',
            'fecha' => '2023/08/30',
            'job_type' => 'Full Time',
            'company_name' => 'Charles Schwab',
            'contingency' => false,
            'location_full' => 'CO-Denver ; TX-Austin ; TX-Dallas ;',
            'url' => 'https://jobs.schwabjobs.com/',
            'perks' => 'remotefriendly ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2 ;',
            'seniority' => 'Senior Level',
            'seniority_slug' => 'senior-level',
            'functional_area' => 'Project Management',
            'functional_area_slug' => 'project-management',
        ]);
        DB::table('jobs')->insert([
            'job_title' => 'Product Owner',
            'fecha' => '2023/08/30',
            'job_type' => 'Full Time',
            'company_name' => 'Charles Schwab',
            'contingency' => false,
            'location_full' => 'Remote ; AZ-Phoenix ; CA-San Francisco ; CO-Denver ; IL-Chicago ; TX-Austin ; TX-Dallas ;',
            'url' => 'https://jobs.schwabjobs.com/',
            'perks' => 'remotefriendly ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2 ;',
            'seniority' => 'Senior Level',
            'seniority_slug' => 'senior-level',
            'functional_area' => 'Other',
            'functional_area_slug' => 'zother',
        ]);
        DB::table('jobs')->insert([
            'job_title' => 'Remote Senior .NET Developer',
            'fecha' => '2023/08/21',
            'job_type' => 'Full Time',
            'company_name' => 'Charles Schwab',
            'contingency' => false,
            'location_full' => 'Remote ;',
            'url' => 'https://jobs.schwabjobs.com/',
            'perks' => 'remotefriendly ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2 ;',
            'seniority' => 'Senior Level',
            'seniority_slug' => 'senior-level',
            'functional_area' => 'Engineering',
            'functional_area_slug' => 'engineering',
        ]);
        DB::table('jobs')->insert([
            'job_title' => 'Senior DLP Engineer',
            'fecha' => '2023/08/21',
            'job_type' => 'Freelance',
            'company_name' => 'Charles Schwab',
            'contingency' => true,
            'location_full' => 'Remote ;',
            'url' => 'https://jobs.schwabjobs.com/',
            'perks' => 'remotefriendly ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2 ;',
            'seniority' => 'Senior Level',
            'seniority_slug' => 'senior-level',
            'functional_area' => 'Engineering',
            'functional_area_slug' => 'engineering',
        ]);
        DB::table('jobs')->insert([
            'job_title' => 'Senior Software Engineer (Java)',
            'fecha' => '2023/08/19',
            'job_type' => 'Full Time',
            'company_name' => 'Charles Schwab',
            'contingency' => false,
            'location_full' => 'TX-Dallas ;',
            'url' => 'https://jobs.schwabjobs.com/',
            'perks' => 'remotefriendly ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2 ;',
            'seniority' => 'Senior Level',
            'seniority_slug' => 'senior-level',
            'functional_area' => 'Engineering',
            'functional_area_slug' => 'engineering',
        ]);
        DB::table('jobs')->insert([
            'job_title' => '.NET Developer III',
            'fecha' => '2023/08/19',
            'job_type' => 'Full Time',
            'company_name' => 'Charles Schwab',
            'contingency' => false,
            'location_full' => 'TX-Dallas ;',
            'url' => 'https://jobs.schwabjobs.com/',
            'perks' => 'remotefriendly ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2 ;',
            'seniority' => 'Mid Level',
            'seniority_slug' => 'mid-level',
            'functional_area' => 'IT & Cybersecurity',
            'functional_area_slug' => 'it-cybersecurity',
        ]);
        DB::table('jobs')->insert([
            'job_title' => 'Salesforce Developer',
            'fecha' => '2023/08/19',
            'job_type' => 'Temporary',
            'company_name' => 'Charles Schwab',
            'contingency' => true,
            'location_full' => 'AZ-Phoenix ; NE-Omaha ; TX-Austin ; TX-Dallas ;',
            'url' => 'https://jobs.schwabjobs.com/',
            'perks' => 'remotefriendly ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2 ;',
            'seniority' => 'Mid Level',
            'seniority_slug' => 'mid-level',
            'functional_area' => 'IT & Cybersecurity',
            'functional_area_slug' => 'it-cybersecurity',
        ]);
        DB::table('jobs')->insert([
            'job_title' => 'Marketing Operations Manager',
            'fecha' => '2023/08/23',
            'job_type' => 'Internship',
            'company_name' => 'Chronosphere',
            'contingency' => false,
            'location_full' => 'Remote ;',
            'url' => 'https://chronosphere.io/',
            'perks' => '',
            'seniority' => 'Mid Level',
            'seniority_slug' => 'mid-level',
            'functional_area' => 'Marketing',
            'functional_area_slug' => 'marketing',
        ]);
        DB::table('jobs')->insert([
            'job_title' => 'Website Marketing Manager',
            'fecha' => '2023/08/23',
            'job_type' => 'Internship',
            'company_name' => 'Chronosphere',
            'contingency' => false,
            'location_full' => 'Remote ;',
            'url' => 'https://chronosphere.io/',
            'perks' => '',
            'seniority' => 'Junior Level',
            'seniority_slug' => 'entry-level',
            'functional_area' => 'Marketing',
            'functional_area_slug' => 'marketing',
        ]);
        DB::table('jobs')->insert([
            'job_title' => 'Senior Product Designer',
            'fecha' => '2023/08/14',
            'job_type' => 'Full Time',
            'company_name' => 'Chronosphere',
            'contingency' => false,
            'location_full' => 'Remote ;',
            'url' => 'https://chronosphere.io/',
            'perks' => '',
            'seniority' => 'Mid Level',
            'seniority_slug' => 'mid-level',
            'functional_area' => 'Product',
            'functional_area_slug' => 'product',
        ]);
        DB::table('jobs')->insert([
            'job_title' => 'Senior Product Designer',
            'fecha' => '2023/08/14',
            'job_type' => 'Freelance',
            'company_name' => 'Chronosphere',
            'contingency' => true,
            'location_full' => 'NY-New York City ;',
            'url' => 'https://chronosphere.io/',
            'perks' => '',
            'seniority' => 'Junior Level',
            'seniority_slug' => 'entry-level',
            'functional_area' => 'People Ops',
            'functional_area_slug' => 'people-ops',
        ]);
        DB::table('jobs')->insert([
            'job_title' => 'Senior Software Engineer - Platform',
            'fecha' => '2023/08/12',
            'job_type' => 'Full Time',
            'company_name' => 'Chronosphere',
            'contingency' => false,
            'location_full' => 'Remote ;',
            'url' => 'https://chronosphere.io/',
            'perks' => '',
            'seniority' => 'Mid Level',
            'seniority_slug' => 'mid-level',
            'functional_area' => 'Engineering',
            'functional_area_slug' => 'engineering',
        ]);
        DB::table('jobs')->insert([
            'job_title' => 'Senior Software Engineer - Infrastructure',
            'fecha' => '2023/08/12',
            'job_type' => 'Freelance',
            'company_name' => 'Chronosphere',
            'contingency' => true,
            'location_full' => 'Remote ;',
            'url' => 'https://chronosphere.io/',
            'perks' => '',
            'seniority' => 'Mid Level',
            'seniority_slug' => 'mid-level',
            'functional_area' => 'Engineering',
            'functional_area_slug' => 'engineering***',
        ]);
        DB::table('jobs')->insert([
            'job_title' => 'Mobile App Product Manager',
            'fecha' => '2023/08/19',
            'job_type' => 'Full Time',
            'company_name' => 'Common Sense Media',
            'contingency' => false,
            'location_full' => 'Remote ;',
            'url' => 'http://www.commonsensemedia.org',
            'perks' => '',
            'seniority' => 'Mid Level',
            'seniority_slug' => 'mid-level',
            'functional_area' => 'Engineering',
            'functional_area_slug' => 'engineering',
        ]);
        DB::table('jobs')->insert([
            'job_title' => 'Nonprofit Success Manager',
            'fecha' => '2023/08/14',
            'job_type' => 'Full Time',
            'company_name' => 'Community First Foundation',
            'contingency' => false,
            'location_full' => 'Hybrid ; CO-Denver ;',
            'url' => 'https://www.communityfirstfoundation.org/',
            'perks' => '',
            'seniority' => 'Mid Level',
            'seniority_slug' => 'mid-level',
            'functional_area' => 'Support',
            'functional_area_slug' => 'support',
        ]);
        DB::table('jobs')->insert([
            'job_title' => 'Senior Technical Writer',
            'fecha' => '2023/08/14',
            'job_type' => 'Temporary',
            'company_name' => 'CrowdStrike',
            'contingency' => true,
            'location_full' => 'Remote ;',
            'url' => 'https://www.crowdstrike.com/careers/',
            'perks' => 'remotefriendly ; paidparentalleave ; ',
            'seniority' => 'Junior Level',
            'seniority_slug' => 'entry-level',
            'functional_area' => 'Product',
            'functional_area_slug' => 'product',
        ]);
        DB::table('jobs')->insert([
            'job_title' => 'Senior Software Engineer - Frontend',
            'fecha' => '2023/08/14',
            'job_type' => 'Freelance',
            'company_name' => 'CrowdStrike',
            'contingency' => true,
            'location_full' => 'Remote ;',
            'url' => 'https://www.crowdstrike.com/careers/',
            'perks' => 'remotefriendly ; paidparentalleave ; ',
            'seniority' => 'Mid Level',
            'seniority_slug' => 'mid-level',
            'functional_area' => 'Engineering',
            'functional_area_slug' => 'engineering',
        ]);
        DB::table('jobs')->insert([
            'job_title' => 'Head of Corporate Communications',
            'fecha' => '2023/08/14',
            'job_type' => 'Full Time',
            'company_name' => 'CrowdStrike',
            'contingency' => false,
            'location_full' => 'Remote ;',
            'url' => 'https://www.crowdstrike.com/careers/',
            'perks' => 'remotefriendly ; paidparentalleave ; ',
            'seniority' => 'Management',
            'seniority_slug' => 'management',
            'functional_area' => 'Marketing',
            'functional_area_slug' => 'marketing',
        ]);
        DB::table('jobs')->insert([
            'job_title' => 'Sr Manager GTM G&A Talent Team',
            'fecha' => '2023/08/14',
            'job_type' => 'Full Time',
            'company_name' => 'CrowdStrike',
            'contingency' => false,
            'location_full' => 'Remote ;',
            'url' => 'https://www.crowdstrike.com/careers/',
            'perks' => 'remotefriendly ; paidparentalleave ; ',
            'seniority' => 'Mid Level',
            'seniority_slug' => 'mid-level',
            'functional_area' => 'People Ops',
            'functional_area_slug' => 'people-ops',
        ]);
        DB::table('jobs')->insert([
            'job_title' => 'Product Marketing Manager',
            'fecha' => '2023/08/23',
            'job_type' => 'Full Time',
            'company_name' => 'Discord',
            'contingency' => false,
            'location_full' => 'Remote ;',
            'url' => 'https://discord.com/careers',
            'perks' => 'remotefriendly ; paidparentalleave ;  womenintecherg ; lgbtqierg-2 ;',
            'seniority' => 'Mid Level',
            'seniority_slug' => 'mid-level',
            'functional_area' => 'Marketing',
            'functional_area_slug' => 'marketing',
        ]);
        DB::table('jobs')->insert([
            'job_title' => 'Customer Solutions Engineer',
            'fecha' => '2023/08/14',
            'job_type' => 'Full Time',
            'company_name' => 'Discord',
            'contingency' => false,
            'location_full' => 'Remote ;',
            'url' => 'https://discord.com/careers',
            'perks' => 'remotefriendly ; paidparentalleave ;  womenintecherg ; lgbtqierg-2 ;',
            'seniority' => 'Mid Level',
            'seniority_slug' => 'mid-level',
            'functional_area' => 'Other',
            'functional_area_slug' => 'zother',
        ]);
        DB::table('jobs')->insert([
            'job_title' => 'Technical Content Writer',
            'fecha' => '2023/08/14',
            'job_type' => 'Full Time',
            'company_name' => 'Discord',
            'contingency' => false,
            'location_full' => 'Remote ;',
            'url' => 'https://discord.com/careers',
            'perks' => 'remotefriendly ; paidparentalleave ;  womenintecherg ; lgbtqierg-2 ;',
            'seniority' => 'Junior Level',
            'seniority_slug' => 'entry-level',
            'functional_area' => 'Marketing',
            'functional_area_slug' => 'marketing',
        ]);
        DB::table('jobs')->insert([
            'job_title' => 'Lead Analyst',
            'fecha' => '2023/08/28',
            'job_type' => 'Full Time',
            'company_name' => 'Federal Reserve Bank of San Francisco',
            'contingency' => false,
            'location_full' => 'CA-San Francisco ;',
            'url' => 'https://www.frbsf.org/our-district/careers/',
            'perks' => '',
            'seniority' => 'Mid Level',
            'seniority_slug' => 'mid-level',
            'functional_area' => 'Project Management',
            'functional_area_slug' => 'project-management',
        ]);
        DB::table('jobs')->insert([
            'job_title' => 'Sr. Solution Architect',
            'fecha' => '2023/08/28',
            'job_type' => 'Full Time',
            'company_name' => 'Federal Reserve Bank of San Francisco',
            'contingency' => false,
            'location_full' => 'CA-San Francisco ;',
            'url' => 'https://www.frbsf.org/our-district/careers/',
            'perks' => '',
            'seniority' => 'Senior Level',
            'seniority_slug' => 'senior-level',
            'functional_area' => 'IT & Cybersecurity',
            'functional_area_slug' => 'it-cybersecurity',
        ]);
        DB::table('jobs')->insert([
            'job_title' => 'Sr .Net Developer w/ AWS experience',
            'fecha' => '2023/08/28',
            'job_type' => 'Full Time',
            'company_name' => 'Federal Reserve Bank of San Francisco',
            'contingency' => false,
            'location_full' => 'CA-San Francisco ;',
            'url' => 'https://www.frbsf.org/our-district/careers/',
            'perks' => '',
            'seniority' => 'Senior Level',
            'seniority_slug' => 'senior-level',
            'functional_area' => 'IT & Cybersecurity',
            'functional_area_slug' => 'it-cybersecurity',
        ]);
        DB::table('jobs')->insert([
            'job_title' => 'Sr Manager, App Dev',
            'fecha' => '2023/08/13',
            'job_type' => 'Internship',
            'company_name' => 'Federal Reserve Bank of San Francisco',
            'contingency' => false,
            'location_full' => 'CA-San Francisco ;',
            'url' => 'https://www.frbsf.org/our-district/careers/',
            'perks' => '',
            'seniority' => 'Senior Level',
            'seniority_slug' => 'senior-level',
            'functional_area' => 'IT & Cybersecurity',
            'functional_area_slug' => 'it-cybersecurity',
        ]);
        DB::table('jobs')->insert([
            'job_title' => 'Sr. Solution Architect',
            'fecha' => '2023/08/13',
            'job_type' => 'Full Time',
            'company_name' => 'Federal Reserve Bank of San Francisco',
            'contingency' => false,
            'location_full' => 'CA-San Francisco ;',
            'url' => 'https://www.frbsf.org/our-district/careers/',
            'perks' => '',
            'seniority' => 'Senior Level',
            'seniority_slug' => 'senior-level',
            'functional_area' => 'IT & Cybersecurity',
            'functional_area_slug' => 'it-cybersecurity',
        ]);
        DB::table('jobs')->insert([
            'job_title' => 'Lead DevOps Engineer',
            'fecha' => '2023/08/13',
            'job_type' => 'Full Time',
            'company_name' => 'Federal Reserve Bank of San Francisco',
            'contingency' => false,
            'location_full' => 'CA-San Francisco ;',
            'url' => 'https://www.frbsf.org/our-district/careers/',
            'perks' => '',
            'seniority' => 'Senior Level',
            'seniority_slug' => 'senior-level',
            'functional_area' => 'IT & Cybersecurity',
            'functional_area_slug' => 'it-cybersecurity',
        ]);
        DB::table('jobs')->insert([
            'job_title' => 'Product Manager',
            'fecha' => '2023/08/27',
            'job_type' => 'Freelance',
            'company_name' => 'Firemon',
            'contingency' => true,
            'location_full' => 'Remote ;',
            'url' => 'https://www.firemon.com',
            'perks' => '',
            'seniority' => 'Senior Level',
            'seniority_slug' => 'senior-level',
            'functional_area' => 'Product',
            'functional_area_slug' => 'product',
        ]);
        DB::table('jobs')->insert([
            'job_title' => 'Engineering Lead Manager',
            'fecha' => '2023/08/20',
            'job_type' => 'Full Time',
            'company_name' => 'GFiber',
            'contingency' => false,
            'location_full' => 'TN-Nashville ;',
            'url' => 'https://fiber.google.com/',
            'perks' => '',
            'seniority' => 'Senior Level',
            'seniority_slug' => 'senior-level',
            'functional_area' => 'Operations',
            'functional_area_slug' => 'operations',
        ]);
        DB::table('jobs')->insert([
            'job_title' => 'Platform Engineering Manager',
            'fecha' => '2023/08/29',
            'job_type' => 'Full Time',
            'company_name' => 'Honeycomb.io',
            'contingency' => false,
            'location_full' => 'Remote ;',
            'url' => 'https://www.honeycomb.io/',
            'perks' => 'remotefriendly ; unlimitedvacation ; paidparentalleave ; latinxintech ;',
            'seniority' => 'Management',
            'seniority_slug' => 'z-management',
            'functional_area' => 'Engineering',
            'functional_area_slug' => 'engineering',
        ]);
        DB::table('jobs')->insert([
            'job_title' => 'Senior Product Engineer',
            'fecha' => '2023/08/20',
            'job_type' => 'Full Time',
            'company_name' => 'Honeycomb.io',
            'contingency' => false,
            'location_full' => 'Remote ;',
            'url' => 'https://www.honeycomb.io/',
            'perks' => 'remotefriendly ; unlimitedvacation ; paidparentalleave ; latinxintech ;',
            'seniority' => 'Senior Level',
            'seniority_slug' => 'senior-level',
            'functional_area' => 'Engineering',
            'functional_area_slug' => 'engineering',
        ]);
        DB::table('jobs')->insert([
            'job_title' => 'Technical Project Manager - Google Analytics/Digital Analytics',
            'fecha' => '2023/08/26',
            'job_type' => 'Full Time',
            'company_name' => 'InfoTrust',
            'contingency' => false,
            'location_full' => 'Remote ; US;',
            'url' => 'https://infotrust.com/',
            'perks' => '',
            'seniority' => 'Mid Level',
            'seniority_slug' => 'mid-Level',
            'functional_area' => 'Other',
            'functional_area_slug' => 'zother',
        ]);
        DB::table('jobs')->insert([
            'job_title' => 'DevOps Engineer',
            'fecha' => '2023/08/13',
            'job_type' => 'Internship',
            'company_name' => 'iZotope',
            'contingency' => false,
            'location_full' => 'MA-Boston ;',
            'url' => 'http://izotope.com',
            'perks' => 'remotefriendly ; unlimitedvacation ; paidparentalleave ;',
            'seniority' => 'Mid Level',
            'seniority_slug' => 'mid-Level',
            'functional_area' => 'IT & Cybersecurity',
            'functional_area_slug' => 'it-cybersecurity',
        ]);
        DB::table('jobs')->insert([
            'job_title' => 'Software Engineering Manager',
            'fecha' => '2023/08/30',
            'job_type' => 'Full Time',
            'company_name' => 'Latinas in Tech',
            'contingency' => false,
            'location_full' => 'TX-Austin ; TX-Dallas ;',
            'url' => 'https://jobs.schwabjobs.com/',
            'perks' => 'remotefriendly ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2 ;',
            'seniority' => 'Management',
            'seniority_slug' => 'z-management',
            'functional_area' => 'Engineering',
            'functional_area_slug' => 'engineering',
        ]);
        DB::table('jobs')->insert([
            'job_title' => 'Director of Marketing Operations',
            'fecha' => '2023/08/28',
            'job_type' => 'Internship',
            'company_name' => 'Lattice',
            'contingency' => false,
            'location_full' => 'Remote ;',
            'url' => 'https://lattice.com/',
            'perks' => '',
            'seniority' => 'Management',
            'seniority_slug' => 'z-management',
            'functional_area' => 'Marketing',
            'functional_area_slug' => 'marketing',
        ]);
        DB::table('jobs')->insert([
            'job_title' => 'Vice President, Product and Segment Marketing',
            'fecha' => '2023/08/28',
            'job_type' => 'Full Time',
            'company_name' => 'Lattice',
            'contingency' => false,
            'location_full' => 'Remote ; CA-San Francisco ;',
            'url' => 'https://lattice.com/',
            'perks' => '',
            'seniority' => 'Management',
            'seniority_slug' => 'z-management',
            'functional_area' => 'Marketing',
            'functional_area_slug' => 'marketing',
        ]);
        DB::table('jobs')->insert([
            'job_title' => 'Staff Software Engineer, iOS',
            'fecha' => '2023/08/19',
            'job_type' => 'Full Time',
            'company_name' => 'Macy"s',
            'contingency' => false,
            'location_full' => 'Remote ; CA-San Francisco ; UT-Other ; WA-Seattle ;',
            'url' => 'https://ebwh.fa.us2.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1001',
            'perks' => 'remotefriendly ; unlimitedvacation ; paidparentalleave ; womenintecherg ; ',
            'seniority' => 'Senior Level',
            'seniority_slug' => 'senior-level',
            'functional_area' => 'Engineering',
            'functional_area_slug' => 'engineering',
        ]);
        DB::table('jobs')->insert([
            'job_title' => 'Strategic Finance Manager Operations',
            'fecha' => '2023/08/19',
            'job_type' => 'Freelance',
            'company_name' => 'Macy"s',
            'contingency' => true,
            'location_full' => 'CA-San Francisco ;',
            'url' => 'https://ebwh.fa.us2.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1002',
            'perks' => 'remotefriendly ; unlimitedvacation ; paidparentalleave ; womenintecherg ; ',
            'seniority' => 'Mid Level',
            'seniority_slug' => 'mid-level',
            'functional_area' => 'Finance',
            'functional_area_slug' => 'finance',
        ]);
        DB::table('jobs')->insert([
            'job_title' => 'Strategic Finance Senior Associate',
            'fecha' => '2023/08/19',
            'job_type' => 'Full Time',
            'company_name' => 'Macy"s',
            'contingency' => false,
            'location_full' => 'Remote ;',
            'url' => 'https://ebwh.fa.us2.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1003',
            'perks' => 'remotefriendly ; unlimitedvacation ; paidparentalleave ; womenintecherg ; ',
            'seniority' => 'Mid Level',
            'seniority_slug' => 'mid-level',
            'functional_area' => 'Finance',
            'functional_area_slug' => 'finance',
        ]);
        DB::table('jobs')->insert([
            'job_title' => 'Associate, Capital Management',
            'fecha' => '2023/08/19',
            'job_type' => 'Freelance',
            'company_name' => 'Macy"s',
            'contingency' => true,
            'location_full' => 'Remote ; CA-San Francisco ; NY-New York City ; UT-Salt Lake City ;',
            'url' => 'https://ebwh.fa.us2.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1004',
            'perks' => 'remotefriendly ; unlimitedvacation ; paidparentalleave ; womenintecherg ; ',
            'seniority' => 'Mid Level',
            'seniority_slug' => 'mid-level',
            'functional_area' => 'Finance',
            'functional_area_slug' => 'finance',
        ]);
        DB::table('jobs')->insert([
            'job_title' => 'Software Engineer (L5) - AVTnT (Audio Video Test & Tools)',
            'fecha' => '2023/08/30',
            'job_type' => 'Full Time',
            'company_name' => 'Netflix',
            'contingency' => false,
            'location_full' => 'CA-Other ;',
            'url' => 'https://jobs.netflix.com/?utm_campaign=LIHomePage&utm_source=linkedin',
            'perks' => 'remotefriendly ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2 ;',
            'seniority' => 'Mid Level',
            'seniority_slug' => 'mid-level',
            'functional_area' => 'Engineering',
            'functional_area_slug' => 'engineering',
        ]);
        DB::table('jobs')->insert([
            'job_title' => 'Senior Manager, Site Reliability Engineering',
            'fecha' => '2023/08/29',
            'job_type' => 'Full Time',
            'company_name' => 'Netflix',
            'contingency' => false,
            'location_full' => 'Remote ;',
            'url' => 'https://jobs.netflix.com/search',
            'perks' => 'remotefriendly ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2 ;',
            'seniority' => 'Management',
            'seniority_slug' => 'z-management',
            'functional_area' => 'Engineering',
            'functional_area_slug' => 'engineering',
        ]);
        DB::table('jobs')->insert([
            'job_title' => 'Systems Software Engineer (E4) - Device Platform Infrastructure',
            'fecha' => '2023/08/22',
            'job_type' => 'Full Time',
            'company_name' => 'Netflix',
            'contingency' => false,
            'location_full' => 'CA-Other ;',
            'url' => 'https://jobs.netflix.com/?utm_campaign=LIHomePage&utm_source=linkedin',
            'perks' => 'remotefriendly ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2 ;',
            'seniority' => 'Mid Level',
            'seniority_slug' => 'mid-level',
            'functional_area' => 'Engineering',
            'functional_area_slug' => 'engineering',
        ]);
        DB::table('jobs')->insert([
            'job_title' => 'Lead Data Engineer',
            'fecha' => '2023/08/14',
            'job_type' => 'Freelance',
            'company_name' => 'New Relic',
            'contingency' => true,
            'location_full' => 'Remote ;',
            'url' => 'https://newrelic.com/',
            'perks' => 'remotefriendly ; unlimitedvacation ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2 ;',
            'seniority' => 'Senior Level',
            'seniority_slug' => 'senior-level',
            'functional_area' => 'Other',
            'functional_area_slug' => 'zother',
        ]);
        DB::table('jobs')->insert([
            'job_title' => 'Senior Frontend Software Engineer - (Remote)',
            'fecha' => '2023/08/14',
            'job_type' => 'Full Time',
            'company_name' => 'New Relic',
            'contingency' => false,
            'location_full' => 'Remote ;',
            'url' => 'https://newrelic.com/',
            'perks' => 'remotefriendly ; unlimitedvacation ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2 ;',
            'seniority' => 'Senior Level',
            'seniority_slug' => 'senior-level',
            'functional_area' => 'Engineering',
            'functional_area_slug' => 'engineering',
        ]);
        DB::table('jobs')->insert([
            'job_title' => 'Principal Software Engineer',
            'fecha' => '2023/08/29',
            'job_type' => 'Full Time',
            'company_name' => 'Nike',
            'contingency' => false,
            'location_full' => 'OR-Portland ;',
            'url' => 'http://jobs.nike.com',
            'perks' => 'remotefriendly ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2 ;',
            'seniority' => 'Senior Level',
            'seniority_slug' => 'senior-level',
            'functional_area' => 'Engineering',
            'functional_area_slug' => 'engineering',
        ]);
        DB::table('jobs')->insert([
            'job_title' => 'Principal Data Engineer',
            'fecha' => '2023/08/29',
            'job_type' => 'Temporary',
            'company_name' => 'Nike',
            'contingency' => true,
            'location_full' => 'Remote ;',
            'url' => 'http://jobs.nike.com',
            'perks' => 'remotefriendly ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2 ;',
            'seniority' => 'Senior Level',
            'seniority_slug' => 'senior-level',
            'functional_area' => 'Engineering',
            'functional_area_slug' => 'engineering',
        ]);
        DB::table('jobs')->insert([
            'job_title' => 'Director of Engineering - AI/ML Technology Foundation',
            'fecha' => '2023/08/29',
            'job_type' => 'Freelance',
            'company_name' => 'Nike',
            'contingency' => true,
            'location_full' => 'Remote ;',
            'url' => 'http://jobs.nike.com',
            'perks' => 'remotefriendly ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2 ;',
            'seniority' => 'Management',
            'seniority_slug' => 'z-management',
            'functional_area' => 'Engineering',
            'functional_area_slug' => 'engineering',
        ]);
        DB::table('jobs')->insert([
            'job_title' => 'Principal, Responsible Technology',
            'fecha' => '2023/08/21',
            'job_type' => 'Full Time',
            'company_name' => 'Omidyar Network',
            'contingency' => false,
            'location_full' => 'Hybrid ; CA-San Francisco ; CA-Other ; DC-Washington ; DC-Other ; MD-Baltimore ; MD-Other ; NY-New York City ; NY-Other ; VA-Arlington ; VA-Other ;',
            'url' => 'https://omidyar.com/',
            'perks' => '',
            'seniority' => 'Mid Level',
            'seniority_slug' => 'mid-level',
            'functional_area' => 'Business Strategy',
            'functional_area_slug' => 'business-strategy',
        ]);
        DB::table('jobs')->insert([
            'job_title' => 'Senior Product Manager',
            'fecha' => '2023/08/21',
            'job_type' => 'Full Time',
            'company_name' => 'Orum.io',
            'contingency' => false,
            'location_full' => 'Remote ;',
            'url' => 'https://orum.io/',
            'perks' => '',
            'seniority' => 'Mid Level',
            'seniority_slug' => 'mid-level',
            'functional_area' => 'Product',
            'functional_area_slug' => 'product',
        ]);
        DB::table('jobs')->insert([
            'job_title' => 'LAC Software Engineering Manager',
            'fecha' => '2023/08/30',
            'job_type' => 'Full Time',
            'company_name' => 'Qualtrics',
            'contingency' => false,
            'location_full' => 'Mexico ;',
            'url' => 'http://qualtrics.com',
            'perks' => 'remotefriendly ; paidparentalleave ; womenintecherg ; lgbtqierg-2 ;',
            'seniority' => 'Management',
            'seniority_slug' => 'z-management',
            'functional_area' => 'Engineering',
            'functional_area_slug' => 'engineering',
        ]);
        DB::table('jobs')->insert([
            'job_title' => 'Manager, Partnership Success',
            'fecha' => '2023/08/19',
            'job_type' => 'Freelance',
            'company_name' => 'SoFi',
            'contingency' => true,
            'location_full' => 'CA-San Francisco ; UT-Salt Lake City ; WA-Seattle ;',
            'url' => 'http://www.sofi.com/careers',
            'perks' => 'remotefriendly ; unlimitedvacation ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2 ;',
            'seniority' => 'Mid Level',
            'seniority_slug' => 'mid-level',
            'functional_area' => 'Business Dev / Partnerships',
            'functional_area_slug' => 'business-dev-partnerships',
        ]);
        DB::table('jobs')->insert([
            'job_title' => 'Sr. Data Scientist (Relay)',
            'fecha' => '2023/08/19',
            'job_type' => 'Freelance',
            'company_name' => 'SoFi',
            'contingency' => true,
            'location_full' => 'Remote ; CA-San Francisco ; NY-New York City ; UT-Other ; WA-Seattle ;',
            'url' => 'http://www.sofi.com/careers',
            'perks' => 'remotefriendly ; unlimitedvacation ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2 ;',
            'seniority' => 'Mid Level',
            'seniority_slug' => 'mid-level',
            'functional_area' => 'Data & Analytics',
            'functional_area_slug' => 'data-analytics',
        ]);
        DB::table('jobs')->insert([
            'job_title' => 'Senior Software Engineer',
            'fecha' => '2023/08/19',
            'job_type' => 'Full Time',
            'company_name' => 'SoFi',
            'contingency' => false,
            'location_full' => 'UT-Other ;',
            'url' => 'http://www.sofi.com/careers',
            'perks' => 'remotefriendly ; unlimitedvacation ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2 ;',
            'seniority' => 'Senior Level',
            'seniority_slug' => 'senior-level',
            'functional_area' => 'Engineering',
            'functional_area_slug' => 'engineering',
        ]);
        DB::table('jobs')->insert([
            'job_title' => 'People Operations Associate',
            'fecha' => '2023/08/19',
            'job_type' => 'Freelance',
            'company_name' => 'SoFi',
            'contingency' => true,
            'location_full' => 'UT-Salt Lake City ;',
            'url' => 'http://www.sofi.com/careers',
            'perks' => 'remotefriendly ; unlimitedvacation ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2 ;',
            'seniority' => 'Junior Level',
            'seniority_slug' => 'entry-level',
            'functional_area' => 'Human Resources',
            'functional_area_slug' => 'human-resources',
        ]);
        DB::table('jobs')->insert([
            'job_title' => 'Privacy Manager',
            'fecha' => '2023/08/19',
            'job_type' => 'Full Time',
            'company_name' => 'SoFi',
            'contingency' => false,
            'location_full' => 'Remote ;',
            'url' => 'http://www.sofi.com/careers',
            'perks' => 'remotefriendly ; unlimitedvacation ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2 ;',
            'seniority' => 'Management',
            'seniority_slug' => 'z-management',
            'functional_area' => 'Legal',
            'functional_area_slug' => 'legal',
        ]);
        DB::table('jobs')->insert([
            'job_title' => 'Collections Associate - Credit Card',
            'fecha' => '2023/08/19',
            'job_type' => 'Internship',
            'company_name' => 'SoFi',
            'contingency' => false,
            'location_full' => 'FL-Other ; UT-Salt Lake City ;',
            'url' => 'http://www.sofi.com/careers',
            'perks' => 'remotefriendly ; unlimitedvacation ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2 ;',
            'seniority' => 'Junior Level',
            'seniority_slug' => 'entry-level',
            'functional_area' => 'Operations',
            'functional_area_slug' => 'operations',
        ]);
        DB::table('jobs')->insert([
            'job_title' => 'Facilities and Real Estate Manager',
            'fecha' => '2023/08/19',
            'job_type' => 'Full Time',
            'company_name' => 'SoFi',
            'contingency' => false,
            'location_full' => 'CA-San Francisco ;',
            'url' => 'http://www.sofi.com/careers',
            'perks' => 'remotefriendly ; unlimitedvacation ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2 ;',
            'seniority' => 'Management',
            'seniority_slug' => 'z-management',
            'functional_area' => 'Operations',
            'functional_area_slug' => 'operations',
        ]);
        DB::table('jobs')->insert([
            'job_title' => 'Manager, Fraud Investigations',
            'fecha' => '2023/08/19',
            'job_type' => 'Full Time',
            'company_name' => 'SoFi',
            'contingency' => false,
            'location_full' => 'CA-Other ; FL-Other ; TX-Dallas ; UT-Salt Lake City ;',
            'url' => 'http://www.sofi.com/careers',
            'perks' => 'remotefriendly ; unlimitedvacation ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2 ;',
            'seniority' => 'Management',
            'seniority_slug' => 'z-management',
            'functional_area' => 'Operations',
            'functional_area_slug' => 'operations',
        ]);
        DB::table('jobs')->insert([
            'job_title' => 'Member Service Representative- SoFi Money',
            'fecha' => '2023/08/19',
            'job_type' => 'Internship',
            'company_name' => 'SoFi',
            'contingency' => false,
            'location_full' => 'FL-Other ;',
            'url' => 'http://www.sofi.com/careers',
            'perks' => 'remotefriendly ; unlimitedvacation ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2 ;',
            'seniority' => 'Junior Level',
            'seniority_slug' => 'entry-level',
            'functional_area' => 'Operations',
            'functional_area_slug' => 'operations',
        ]);
        DB::table('jobs')->insert([
            'job_title' => 'Senior Business Operations Analyst',
            'fecha' => '2023/08/19',
            'job_type' => 'Full Time',
            'company_name' => 'SoFi',
            'contingency' => false,
            'location_full' => 'FL-Other ; UT-Salt Lake City ;',
            'url' => 'http://www.sofi.com/careers',
            'perks' => 'remotefriendly ; unlimitedvacation ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2 ;',
            'seniority' => 'Junior Level',
            'seniority_slug' => 'entry-level',
            'functional_area' => 'Operations',
            'functional_area_slug' => 'operations',
        ]);
        DB::table('jobs')->insert([
            'job_title' => 'Principal Product Manager, SoFi Bank',
            'fecha' => '2023/08/19',
            'job_type' => 'Freelance',
            'company_name' => 'SoFi',
            'contingency' => true,
            'location_full' => 'CA-San Francisco ; UT-Salt Lake City ; WA-Seattle ;',
            'url' => 'http://www.sofi.com/careers',
            'perks' => 'remotefriendly ; unlimitedvacation ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2 ;',
            'seniority' => 'Senior Level',
            'seniority_slug' => 'senior-level',
            'functional_area' => 'Product',
            'functional_area_slug' => 'product',
        ]);
        DB::table('jobs')->insert([
            'job_title' => 'Senior Product Manager, Invest',
            'fecha' => '2023/08/19',
            'job_type' => 'Freelance',
            'company_name' => 'SoFi',
            'contingency' => true,
            'location_full' => 'Remote ; CA-San Francisco ; NY-New York City ; UT-Salt Lake City ; WA-Seattle ;',
            'url' => 'http://www.sofi.com/careers',
            'perks' => 'remotefriendly ; unlimitedvacation ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2 ;',
            'seniority' => 'Management',
            'seniority_slug' => 'z-management',
            'functional_area' => 'Product',
            'functional_area_slug' => 'product',
        ]);
        DB::table('jobs')->insert([
            'job_title' => 'Credit Risk Manager, Risk Management – Credit Card',
            'fecha' => '2023/08/19',
            'job_type' => 'Full Time',
            'company_name' => 'SoFi',
            'contingency' => false,
            'location_full' => 'FL-Other ; TX-Dallas ; UT-Salt Lake City ;',
            'url' => 'http://www.sofi.com/careers',
            'perks' => 'remotefriendly ; unlimitedvacation ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2 ;',
            'seniority' => 'Management',
            'seniority_slug' => 'z-management',
            'functional_area' => 'IT & Cybersecurity',
            'functional_area_slug' => 'it-cybersecurity',
        ]);
        DB::table('jobs')->insert([
            'job_title' => 'Senior Risk Data Analyst, Fraud Prevention',
            'fecha' => '2023/08/19',
            'job_type' => 'Full Time',
            'company_name' => 'SoFi',
            'contingency' => false,
            'location_full' => 'Remote ; CA-San Francisco ; NY-New York City ; TX-Dallas ;',
            'url' => 'http://www.sofi.com/careers',
            'perks' => 'remotefriendly ; unlimitedvacation ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2 ;',
            'seniority' => 'Junior Level',
            'seniority_slug' => 'entry-level',
            'functional_area' => 'IT & Cybersecurity',
            'functional_area_slug' => 'it-cybersecurity',
        ]);
        DB::table('jobs')->insert([
            'job_title' => 'Senior Sales Manager, Mexico',
            'fecha' => '2023/08/16',
            'job_type' => 'Internship',
            'company_name' => 'Sonos',
            'contingency' => false,
            'location_full' => 'Remote ;',
            'url' => 'https://www.sonos.com/en-us/life-at-sonos',
            'perks' => 'remotefriendly ; unlimitedvacation ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2 ;',
            'seniority' => 'Mid Level',
            'seniority_slug' => 'mid-level',
            'functional_area' => 'Sales',
            'functional_area_slug' => 'sales',
        ]);
        DB::table('jobs')->insert([
            'job_title' => 'Senior QA Engineer',
            'fecha' => '2023/08/16',
            'job_type' => 'Freelance',
            'company_name' => 'Sovos',
            'contingency' => true,
            'location_full' => 'MA-Other ;',
            'url' => 'https://hrbrg.co/gpi756',
            'perks' => '',
            'seniority' => 'Senior Level',
            'seniority_slug' => 'senior-level',
            'functional_area' => 'IT & Cybersecurity',
            'functional_area_slug' => 'it-cybersecurity',
        ]);
        DB::table('jobs')->insert([
            'job_title' => 'Software Engineer III - .NET',
            'fecha' => '2023/08/15',
            'job_type' => 'Freelance',
            'company_name' => 'Sovos',
            'contingency' => true,
            'location_full' => 'MA-Other ;',
            'url' => 'https://hrbrg.co/gpi756',
            'perks' => '',
            'seniority' => 'Mid Level',
            'seniority_slug' => 'mid-level',
            'functional_area' => 'IT & Cybersecurity',
            'functional_area_slug' => 'it-cybersecurity',
        ]);
        DB::table('jobs')->insert([
            'job_title' => 'Manager, UX',
            'fecha' => '2023/08/15',
            'job_type' => 'Full Time',
            'company_name' => 'Sovos',
            'contingency' => false,
            'location_full' => 'GA-Atlanta ;',
            'url' => 'https://hrbrg.co/gpi756',
            'perks' => '',
            'seniority' => 'Management',
            'seniority_slug' => 'z-management',
            'functional_area' => 'IT & Cybersecurity',
            'functional_area_slug' => 'it-cybersecurity',
        ]);
        DB::table('jobs')->insert([
            'job_title' => 'Senior Policy Admin & Billing Developer',
            'fecha' => '2023/08/28',
            'job_type' => 'Internship',
            'company_name' => 'State Compensation Insurance Fund',
            'contingency' => false,
            'location_full' => 'CA-Other ;',
            'url' => 'http://statefundca.com',
            'perks' => 'remotefriendly ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2 ;',
            'seniority' => 'Senior Level',
            'seniority_slug' => 'senior-level',
            'functional_area' => 'IT & Cybersecurity',
            'functional_area_slug' => 'it-cybersecurity',
        ]);
        DB::table('jobs')->insert([
            'job_title' => 'Senior Director Product Management',
            'fecha' => '2023/08/16',
            'job_type' => 'Full Time',
            'company_name' => 'The Home Depot',
            'contingency' => false,
            'location_full' => 'Remote ;',
            'url' => 'http://careers.homedepot.com/technology',
            'perks' => 'remotefriendly ; paidparentalleave ; latinxintech ; lgbtqierg-2 ;',
            'seniority' => 'Senior Level',
            'seniority_slug' => 'senior-level',
            'functional_area' => 'Product',
            'functional_area_slug' => 'product',
        ]);
        DB::table('jobs')->insert([
            'job_title' => 'Sr. Product Manager',
            'fecha' => '2023/08/15',
            'job_type' => 'Temporary',
            'company_name' => 'The Home Depot',
            'contingency' => true,
            'location_full' => 'Remote ;',
            'url' => 'http://careers.homedepot.com/technology',
            'perks' => 'remotefriendly ; paidparentalleave ; latinxintech ; lgbtqierg-2 ;',
            'seniority' => 'Mid Level',
            'seniority_slug' => 'mid-level',
            'functional_area' => 'Product',
            'functional_area_slug' => 'product',
        ]);
        DB::table('jobs')->insert([
            'job_title' => 'Product Manager',
            'fecha' => '2023/08/15',
            'job_type' => 'Temporary',
            'company_name' => 'The Home Depot',
            'contingency' => true,
            'location_full' => 'Remote ;',
            'url' => 'http://careers.homedepot.com/technology',
            'perks' => 'remotefriendly ; paidparentalleave ; latinxintech ; lgbtqierg-2 ;',
            'seniority' => 'Junior Level',
            'seniority_slug' => 'entry-level',
            'functional_area' => 'Product',
            'functional_area_slug' => 'product',
        ]);
        DB::table('jobs')->insert([
            'job_title' => 'Staff Systems Engineer',
            'fecha' => '2023/08/15',
            'job_type' => 'Internship',
            'company_name' => 'The Home Depot',
            'contingency' => false,
            'location_full' => 'Remote ;',
            'url' => 'http://careers.homedepot.com/technology',
            'perks' => 'remotefriendly ; paidparentalleave ; latinxintech ; lgbtqierg-2 ;',
            'seniority' => 'Mid Level',
            'seniority_slug' => 'mid-level',
            'functional_area' => 'Engineering',
            'functional_area_slug' => 'engineering',
        ]);
        DB::table('jobs')->insert([
            'job_title' => 'Sr. Systems Engineer',
            'fecha' => '2023/08/15',
            'job_type' => 'Full Time',
            'company_name' => 'The Home Depot',
            'contingency' => false,
            'location_full' => 'Remote ;',
            'url' => 'http://careers.homedepot.com/technology',
            'perks' => 'remotefriendly ; paidparentalleave ; latinxintech ; lgbtqierg-2 ;',
            'seniority' => 'Senior Level',
            'seniority_slug' => 'senior-level',
            'functional_area' => 'Engineering',
            'functional_area_slug' => 'engineering',
        ]);
        DB::table('jobs')->insert([
            'job_title' => 'Sr. User Experience Designers',
            'fecha' => '2023/08/15',
            'job_type' => 'Freelance',
            'company_name' => 'The Home Depot',
            'contingency' => true,
            'location_full' => 'Remote ;',
            'url' => 'http://careers.homedepot.com/technology',
            'perks' => 'remotefriendly ; paidparentalleave ; latinxintech ; lgbtqierg-2 ;',
            'seniority' => 'Senior Level',
            'seniority_slug' => 'senior-level',
            'functional_area' => 'Design',
            'functional_area_slug' => 'design',
        ]);
        DB::table('jobs')->insert([
            'job_title' => 'Principal Software Engineer',
            'fecha' => '2023/08/15',
            'job_type' => 'Internship',
            'company_name' => 'The Home Depot',
            'contingency' => false,
            'location_full' => 'Remote ;',
            'url' => 'http://careers.homedepot.com/technology',
            'perks' => 'remotefriendly ; paidparentalleave ; latinxintech ; lgbtqierg-2 ;',
            'seniority' => 'Senior Level',
            'seniority_slug' => 'senior-level',
            'functional_area' => 'Engineering',
            'functional_area_slug' => 'engineering',
        ]);
        DB::table('jobs')->insert([
            'job_title' => 'Member of Technical Staff 2',
            'fecha' => '2023/08/21',
            'job_type' => 'Full Time',
            'company_name' => 'VMWare',
            'contingency' => false,
            'location_full' => 'Remote ;',
            'url' => 'http://www.vmware.com',
            'perks' => '',
            'seniority' => 'Junior Level',
            'seniority_slug' => 'entry-level',
            'functional_area' => 'Engineering',
            'functional_area_slug' => 'engineering',
        ]);
        DB::table('jobs')->insert([
            'job_title' => 'Database Administrator',
            'fecha' => '2023/08/29',
            'job_type' => 'Full Time',
            'company_name' => 'Wikimedia Foundation',
            'contingency' => false,
            'location_full' => 'Remote ;',
            'url' => 'http://wikimediafoundation.org',
            'perks' => '',
            'seniority' => 'Mid Level',
            'seniority_slug' => 'mid-level',
            'functional_area' => 'Engineering',
            'functional_area_slug' => 'engineering',
        ]);
        DB::table('jobs')->insert([
            'job_title' => 'Senior Product Manager, Platform',
            'fecha' => '2023/08/29',
            'job_type' => 'Full Time',
            'company_name' => 'Wikimedia Foundation',
            'contingency' => false,
            'location_full' => 'Remote ;',
            'url' => 'http://wikimediafoundation.org',
            'perks' => '',
            'seniority' => 'Mid Level',
            'seniority_slug' => 'mid-level',
            'functional_area' => 'Product',
            'functional_area_slug' => 'product',
        ]);
        DB::table('jobs')->insert([
            'job_title' => 'Staff Site Reliability Engineer (Traffic)',
            'fecha' => '2023/08/29',
            'job_type' => 'Full Time',
            'company_name' => 'Wikimedia Foundation',
            'contingency' => false,
            'location_full' => 'Remote ;',
            'url' => 'http://wikimediafoundation.org',
            'perks' => '',
            'seniority' => 'Senior Level',
            'seniority_slug' => 'senior-level',
            'functional_area' => 'Engineering',
            'functional_area_slug' => 'engineering',
        ]);
        DB::table('jobs')->insert([
            'job_title' => 'Senior Software Engineer - Structured Data',
            'fecha' => '2023/08/29',
            'job_type' => 'Full Time',
            'company_name' => 'Wikimedia Foundation',
            'contingency' => false,
            'location_full' => 'Remote ;',
            'url' => 'http://wikimediafoundation.org',
            'perks' => '',
            'seniority' => 'Mid Level',
            'seniority_slug' => 'mid-level',
            'functional_area' => 'Engineering',
            'functional_area_slug' => 'engineering',
        ]);
        DB::table('jobs')->insert([
            'job_title' => 'Software Engineer III - Web Team',
            'fecha' => '2023/08/27',
            'job_type' => 'Full Time',
            'company_name' => 'Wikimedia Foundation',
            'contingency' => false,
            'location_full' => 'Remote ;',
            'url' => 'http://wikimediafoundation.org',
            'perks' => '',
            'seniority' => 'Mid Level',
            'seniority_slug' => 'mid-level',
            'functional_area' => 'Product',
            'functional_area_slug' => 'product',
        ]);
        DB::table('jobs')->insert([
            'job_title' => 'Lead Counsel',
            'fecha' => '2023/08/23',
            'job_type' => 'Temporary',
            'company_name' => 'Wikimedia Foundation',
            'contingency' => true,
            'location_full' => 'Remote ;',
            'url' => 'http://wikimediafoundation.org',
            'perks' => '',
            'seniority' => 'Senior Level',
            'seniority_slug' => 'senior-level',
            'functional_area' => 'Legal',
            'functional_area_slug' => 'legal',
        ]);
        DB::table('jobs')->insert([
            'job_title' => 'Data Visualization Specialist (Contract)',
            'fecha' => '2023/08/22',
            'job_type' => 'Full Time',
            'company_name' => 'Wikimedia Foundation',
            'contingency' => false,
            'location_full' => 'Remote ;US ;',
            'url' => 'http://wikimediafoundation.org',
            'perks' => '',
            'seniority' => 'Mid Level',
            'seniority_slug' => 'mid-level',
            'functional_area' => 'Data & Analytics',
            'functional_area_slug' => 'data-analytics',
        ]);
        DB::table('jobs')->insert([
            'job_title' => 'Senior Project Manager (Communications)',
            'fecha' => '2023/08/15',
            'job_type' => 'Temporary',
            'company_name' => 'Wikimedia Foundation',
            'contingency' => true,
            'location_full' => 'Remote ;',
            'url' => 'http://wikimediafoundation.org',
            'perks' => '',
            'seniority' => 'Senior Level',
            'seniority_slug' => 'senior-level',
            'functional_area' => 'Project Management',
            'functional_area_slug' => 'project-management',
        ]);
        DB::table('jobs')->insert([
            'job_title' => 'Data Center Engineer (contract, part-time)',
            'fecha' => '2023/08/12',
            'job_type' => 'Full Time',
            'company_name' => 'Wikimedia Foundation',
            'contingency' => false,
            'location_full' => 'TX-Other ;',
            'url' => 'http://wikimediafoundation.org',
            'perks' => '',
            'seniority' => 'Mid Level',
            'seniority_slug' => 'mid-level',
            'functional_area' => 'Engineering',
            'functional_area_slug' => 'engineering',
        ]);
        DB::table('jobs')->insert([
            'job_title' => 'Integrated Marketing Specialist',
            'fecha' => '2023/08/12',
            'job_type' => 'Full Time',
            'company_name' => 'Wikimedia Foundation',
            'contingency' => false,
            'location_full' => 'Remote ;',
            'url' => 'http://wikimediafoundation.org',
            'perks' => '',
            'seniority' => 'Mid Level',
            'seniority_slug' => 'mid-level',
            'functional_area' => 'Marketing',
            'functional_area_slug' => 'marketing',
        ]);
        DB::table('jobs')->insert([
            'job_title' => 'Legal Fellow (Spring 2023)',
            'fecha' => '2023/08/12',
            'job_type' => 'Full Time',
            'company_name' => 'Wikimedia Foundation',
            'contingency' => false,
            'location_full' => 'Remote ;',
            'url' => 'http://wikimediafoundation.org',
            'perks' => '',
            'seniority' => 'Junior Level',
            'seniority_slug' => 'entry-level',
            'functional_area' => 'Engineering',
            'functional_area_slug' => 'engineering',
        ]);
        DB::table('jobs')->insert([
            'job_title' => 'Aspire Program – Tech Careers for Women',
            'fecha' => '2023/08/14',
            'job_type' => 'Full Time',
            'company_name' => 'Wiley Edge',
            'contingency' => false,
            'location_full' => 'NY-New York City ;',
            'url' => 'https://www.wileyedge.com',
            'perks' => '',
            'seniority' => '',
            'seniority_slug' => '',
            'functional_area' => '',
            'functional_area_slug' => '',
        ]);

    }
}
